# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '题库'},
        ),
    ]
